
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Database } from '@/types/database.types';

const SUPABASE_URL = "https://nqiuicsmuegnxjtggssf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xaXVpY3NtdWVnbnhqdGdnc3NmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNjQ2ODYsImV4cCI6MjA1OTY0MDY4Nn0.yQr9qJPimWv5M6YqtJzu7JLijq3XxaCdw80ocKO0WTE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
