// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkfrbmexmymufqacuwui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrZnJibWV4bXltdWZxYWN1d3VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MDI1MTcsImV4cCI6MjA1ODA3ODUxN30.Mx_iGvZQlcGYaBrJ5J6N1Jd0099-3y_UPx7tLDh39AI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);